### ISSUE TITLE
Error while calling the ToPdf command

### ISSUE THREAD

**Issue by n1k0** [fraoustin/Sublime2pdf#1]
![Capture d e cran 2013-02-22 a 12 05 26](https://f.cloud.github.com/assets/41547/184553/d5c0e098-7cdf-11e2-8954-ea12853267e9.png)

(using SublimeText 2, OSX ML)

**Comment by fraoustin** [comment]
can you send a text that generate error please?

**Comment by n1k0** [comment]
Sure
![Capture d e cran 2013-02-22 a 13 51 22](https://f.cloud.github.com/assets/41547/184845/994d993a-7cee-11e2-9b3f-4240c1b174b3.png)

**Comment by fraoustin** [comment]
can you remove an re-install plugin, i change a management of error

after can you send a screenshot of error

**Comment by n1k0** [comment]
I'm now having this:

![Capture d e cran 2013-02-23 a 11 38 18](https://f.cloud.github.com/assets/41547/187927/487d949e-7da5-11e2-8707-ef1965a7fe81.png)

Text version:

```
Traceback (most recent call last):   File "./2pdf.py", line 126, 
    in run   File "./2pdf.py", line 163, 
    in _run   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/rst2pdf-0.93.dev/rst2pdf/createpdf.py", line 186, 
    in __init__   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/rst2pdf-0.93.dev/rst2pdf/createpdf.py", line 281, 
    in loadStyles   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/rst2pdf-0.93.dev/rst2pdf/styles.py", line 473, 
    in __init__   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/reportlab-2.6/reportlab/lib/styles.py", line 190, 
    in __getitem__ KeyError: u"Style 'bodytext' not found in stylesheet"
```

**Comment by fraoustin** [comment]
this is not same error .... it's strange
you can in file '/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/print.style' after "styles:" the bloc

```
bodytext:
  parent: normal
  spaceBefore: 6
  alignment: TA_JUSTIFY
  hyphenation: true
```

**Comment by n1k0** [comment]
It didn't solve the issue :/ I tried to add the block using 3 different indentation levels with no luck, I keep getting the error

Edit: not the exact same error actually:

```
Traceback (most recent call last):   File "./2pdf.py", line 122, 
    in run   File "./2pdf.py", line 163, 
    in _run   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/rst2pdf-0.93.dev/rst2pdf/createpdf.py", line 186, 
    in __init__   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/rst2pdf-0.93.dev/rst2pdf/createpdf.py", line 281, 
    in loadStyles   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/rst2pdf-0.93.dev/rst2pdf/styles.py", line 523, 
    in __init__   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/rst2pdf-0.93.dev/rst2pdf/styles.py", line 549, 
    in __getitem__   File "/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/libs/reportlab-2.6/reportlab/lib/styles.py", line 190, 
    in __getitem__ KeyError: "Style 'normal' not found  in stylesheet"
```

Edit2: BTW, I didn't found `print.style` in `/Users/niko/Library/Application Support/Sublime Text 2/Packages/Sublime2pdf/print.style` but in `/Users/niko/Library/Application Support/Sublime Text 2/Packages/2pdf/print.style`

**Comment by llanverygranger** [comment]
I also get the same traceback. Thanks to the developers for putting in the effort though. I hope you manage to get a working version soon as this has huge potential :+1:
