### ISSUE TITLE
To PDF command grayed out

### ISSUE THREAD

**Issue by Sharlock93** [fraoustin/Sublime2pdf#2]
when i install the plugin it works okay, but when i restart this happens 
![Untitled](https://f.cloud.github.com/assets/3481015/229652/7e5f1160-86a5-11e2-9e08-f2261e5ae2ac.png)

**Comment by fraoustin** [comment]
Have you a error in console ( press Ctrl+`) after start sublimeText ?
you work on windows?

**Comment by Sharlock93** [comment]
yes im using windows.

this error happens:

Reloading plugin C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\2pdf.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\2pdf.py", line 64, in <module>
    import rst2pdf.createpdf
  File "C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\rst2pdf-0.93.dev\rst2pdf\createpdf.py", line 45, in <module>
    from opt_imports import psyco
  File "C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\rst2pdf-0.93.dev\rst2pdf\opt_imports.py", line 50, in <module>
    from reportlab.platypus.paragraph import Paragraph
  File "C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\reportlab-2.6\reportlab\platypus__init__.py", line 10, in <module>
    from reportlab.platypus.paragraph import Paragraph, cleanBlockQuotedText, ParaLines
  File "C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\reportlab-2.6\reportlab\platypus\paragraph.py", line 9, in <module>
    from unicodedata import category
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by fraoustin** [comment]
you work on windows 8, 7, XP?

**Comment by Sharlock93** [comment]
windows 7

**Comment by fraoustin** [comment]
if you have python27 on computer, can you copied : 
- C:\python27\libs\unicodedata.lib in C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\
- C:\Python27\DLLs\unicodedata.pyd in C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\

**Comment by Sharlock93** [comment]
copied, but not fixed

**Comment by fraoustin** [comment]
I can not reproduce your problem
can you 
- start sublime
- remove package (by control package: remove package)
- stop sublime
- trash C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf
- start sublime
- install package 2pdf and test
- restart sublime
- test ...

**Comment by Sharlock93** [comment]
okay i first removed 2pdf and trashed C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf
then started sublime and installed 2pdf,  here is the log [installing 2pdf](http://paste.ubuntu.com/5595412/), it works but when i restart it stops working, here is the log [after restart](http://paste.ubuntu.com/5595414/)

**Comment by fraoustin** [comment]
Sublime 2 use python 2.6 and f you have python26 (and not 27) on computer, can you copied :

```
C:\python26\libs\unicodedata.lib in C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\
C:\Python26\DLLs\unicodedata.pyd in C:\Users\Sharo\AppData\Roaming\Sublime Text 2\Packages\2pdf\libs\
```

**Comment by Sharlock93** [comment]
Yup that fixed it...thanks

**Comment by fraoustin** [comment]
you work on 64bits ?

**Comment by Sharlock93** [comment]
yes

**Comment by fraoustin** [comment]
can you send me your unicodedata.lib and unicodedata.pyd

**Comment by Sharlock93** [comment]
sure, the files were from python 2.6.5 x64, i download it from [this](http://www.oldapps.com/Python.php?old_python=33) website
[unicodedata](http://www.mediafire.com/download.php?t2y5ogg71lazz6k)

**Comment by lawlist** [comment]
Grayed out on OSX 10.6.8 with ST2.

**Comment by azur29** [comment]
Hello,

Same things for me.
Windows7 64 bit (french)
2pdf was greyed. after replacing the file with the link giving above by Sharlock93, all
became ok.
Thanks for this great functionality.
